Auth:
  Username: root
  Password: 0penBmc
Metrics:
  - Name: Sensors
    Description: 'All Sensors'
    Type: Gauge
    Label: ["ServerAddress", "HostName", "DeviceName", "ReadingType", "ReadingUnits"]
    Datapoint: Sensors.DeviceName
    Result: Reading